# Generated by Django 3.0.2 on 2020-01-29 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Title')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_of_reminder', models.DateTimeField()),
                ('description', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Id')),
                ('contact_no', models.PositiveIntegerField(blank=True, verbose_name='Contact No.')),
                ('sms_no', models.PositiveIntegerField(blank=True, verbose_name='SMS No.')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enable')),
                ('recur_for', models.CharField(blank=True, choices=[('2 days', 2), ('3 days', 3), ('4 days', 4), ('5 days', 5), ('6 days', 6), ('7 days', 7)], max_length=20, verbose_name='Recur for')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reminders.Subjects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
