# Generated by Django 3.0.2 on 2020-01-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminders',
            name='recur_for',
            field=models.CharField(blank=True, choices=[(2, '2 days'), (3, '3 days'), (4, '4 days'), (5, '5 days'), (6, '6 days'), (7, '7 days')], max_length=20, verbose_name='Recur for'),
        ),
        migrations.AlterField(
            model_name='reminders',
            name='subject',
            field=models.CharField(choices=[('Appointment', 'Appointment'), ('Meeting', 'Meeting'), ('Shopping', 'Shopping'), ('Personal', 'Personal'), ('Party', 'Party'), ('Other', 'Other')], max_length=100, verbose_name='Subject'),
        ),
    ]
