# Generated by Django 3.0.2 on 2020-01-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_auto_20200129_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminders',
        ),
    ]
