# Generated by Django 3.0.2 on 2020-01-29 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reminders', '0003_delete_reminders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Title')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_of_reminder', models.DateTimeField()),
                ('subject', models.CharField(choices=[('Appointment', 'Appointment'), ('Meeting', 'Meeting'), ('Shopping', 'Shopping'), ('Personal', 'Personal'), ('Party', 'Party'), ('Other', 'Other')], max_length=100, verbose_name='Subject')),
                ('description', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Id')),
                ('contact_no', models.PositiveIntegerField(blank=True, verbose_name='Contact No.')),
                ('sms_no', models.PositiveIntegerField(blank=True, verbose_name='SMS No.')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enable')),
                ('recur_for', models.CharField(blank=True, choices=[(2, '2 days'), (3, '3 days'), (4, '4 days'), (5, '5 days'), (6, '6 days'), (7, '7 days')], max_length=20, verbose_name='Recur for')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
