# Generated by Django 3.0.2 on 2020-01-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_reminders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminders',
            name='contact_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Contact No.'),
        ),
        migrations.AlterField(
            model_name='reminders',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='reminders',
            name='recur_for',
            field=models.CharField(blank=True, choices=[(2, '2 days'), (3, '3 days'), (4, '4 days'), (5, '5 days'), (6, '6 days'), (7, '7 days')], max_length=20, null=True, verbose_name='Recur for'),
        ),
        migrations.AlterField(
            model_name='reminders',
            name='sms_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='SMS No.'),
        ),
    ]
