# Generated by Django 3.0.2 on 2020-01-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_auto_20200129_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminders',
            name='recur_for',
            field=models.CharField(blank=True, choices=[('2 days', '2 days'), ('3 days', '3 days'), ('4 days', '4 days'), ('5 days', '5 days'), ('6 days', '6 days'), ('7 days', '7 days')], max_length=20, null=True, verbose_name='Recur for'),
        ),
    ]
