# Generated by Django 3.0.2 on 2020-01-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0006_auto_20200129_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminders',
            name='recur_for',
            field=models.CharField(blank=True, choices=[(2, '2 days'), (3, '3 days'), (4, '4 days'), (5, '5 days'), (6, '6 days'), (7, '7 days')], max_length=20, null=True, verbose_name='Recur for'),
        ),
    ]
